# Generated by Django 2.0.1 on 2018-03-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_name', models.CharField(max_length=200)),
                ('news_create_date', models.DateField(auto_now_add=True)),
                ('news_delete_date', models.DateField(auto_now_add=True)),
                ('news_delete_id', models.IntegerField(default=0)),
                ('news_content', models.CharField(max_length=300)),
            ],
        ),
    ]
