# Generated by Django 2.0.1 on 2018-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconId', models.IntegerField()),
                ('iconName', models.CharField(max_length=6)),
                ('iconImage', models.CharField(max_length=200)),
            ],
        ),
    ]
